name: "Bug Report"
description: "Report a technical or visual issue."
labels: ["bug"]
body:
  - type: input
    attributes:
      label: "Page URL"
      description: "The URL of the page where you encountered the issue."
    validations:
      required: true

  - type: input
    attributes:
      label: "Browser"
      description: "Which browser are you using? (e.g., Chrome, Firefox, Safari)"
      placeholder: "Chrome"
    validations:
      required: true

  - type: input
    attributes:
      label: "Operating System"
      description: "What operating system are you using? Include the version if possible."
      placeholder: "Windows 10"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Steps to Reproduce the Issue"
      description: |
        Please describe the issue in detail, including:
        1. What actions led to the issue?
        2. If possible, attach screenshots or videos demonstrating the problem.
      placeholder: |
        1. I clicked on...
        2. [Attach screenshots/videos if available]
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen."
      placeholder: "I expected the page to..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened, including any error messages."
      placeholder: "Instead, I saw..."
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Priority"
      description: "How urgent is this issue?"
      options:
        - "Low (Minor inconvenience)"
        - "Medium (Affects functionality, but there is a workaround)"
        - "High (Major functionality is broken)"
        - "Critical (Site is unusable)"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Additional Context (Optional)"
      description: |
        Provide any extra details, such as:
        - Related links.
        - Previous occurrences of this issue.
        - Workarounds you have tried.
      placeholder: "This issue also happened on [link]."
    validations:
      required: false
